#!/usr/bin/env python3
"""
seo_build.py - one command that keeps the whole site's SEO consistent.

    python tools/seo/seo_build.py            # stamp every page + sitemap/robots/manifest
    python tools/seo/seo_build.py --check    # report only, change nothing
    python tools/seo/seo_build.py --og       # also (re)draw icons/og-default.png

What it does (idempotent - safe to run any number of times):
  * <title>, meta description, canonical, robots, Open Graph, Twitter card and
    JSON-LD are written into ONE marked block per page:
        <!-- SEO:START ... -->  ...  <!-- SEO:END -->
    Any older loose copies of those tags are removed so nothing is duplicated.
  * quiz / assignment / dashboard / 404 pages get noindex; lesson, subject and
    grade pages are indexable and listed in sitemap.xml.
  * writes sitemap.xml, robots.txt and the name in icons/site.webmanifest.
  * internal links of the form  .../index.html  become  .../  (one URL per page).

Everything site-specific (the site NAME, url, social links, per-page copy)
lives in tools/seo/seo_config.json. Change "site_name" there and re-run.
Standard library only (Pillow is optional, just for the share image).
"""
import datetime
import html
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
CONFIG_PATH = os.path.join(HERE, "seo_config.json")
DEFAULT_ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))

START = "<!-- SEO:START (generated by tools/seo/seo_build.py - edit tools/seo/seo_config.json, not this block) -->"
END = "<!-- SEO:END -->"
BLOCK_RE = re.compile(r"[ \t]*<!-- SEO:START.*?<!-- SEO:END -->[ \t]*\r?\n?", re.S)

SKIP_DIRS = {"tools", ".git", "node_modules", "Docs", "packaged", "__pycache__"}
ARABIC_RE = re.compile(r"[\u0600-\u06FF]")


# --------------------------------------------------------------------------- config
def load_config():
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    cfg["site_url"] = cfg["site_url"].rstrip("/")
    return cfg


def fmt(cfg, text, **extra):
    """Fill {site_name}/{author_name}/... placeholders in config strings."""
    out = text.replace("{site_name}", cfg["site_name"]).replace("{author_name}", cfg["author_name"])
    for k, v in extra.items():
        out = out.replace("{" + k + "}", str(v))
    return out


# --------------------------------------------------------------------------- text helpers
def read(path):
    with open(path, "r", encoding="utf-8", newline="") as f:
        return f.read()


def write(path, text):
    with open(path, "w", encoding="utf-8", newline="") as f:
        f.write(text)


def esc(s):
    return html.escape(s, quote=True)


def squash(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", s or ""))).strip()


def fix_text(cfg, s):
    s = squash(s).replace("|", "\u2013")
    s = re.sub(r"\s+", " ", s)
    for bad, good in cfg.get("text_fixes", {}).items():
        s = s.replace(bad, good)
    for pat, good in cfg.get("text_fixes_regex", {}).items():
        s = re.sub(pat, good, s)
    s = re.sub(r"(^|\s[\u2013\u2014-]\s)([a-z])", lambda m: m.group(1) + m.group(2).upper(), s)
    return s.strip()


def trim(s, n):
    s = squash(s)
    if len(s) <= n:
        return s
    window = s[:n]
    end = max(window.rfind(". "), window.rfind("\u06d4 "), window.rfind("? "), window.rfind("! "))
    if end == -1 and window.endswith("."):
        end = n - 1
    if end >= int(n * 0.6):
        return window[: end + 1]
    cut = s[: n - 1].rsplit(" ", 1)[0].rstrip(" ,;:-\u2013\u2014.")
    return cut + "\u2026"


# --------------------------------------------------------------------------- site walking
def walk_pages(root):
    out = []
    for dp, dn, fn in os.walk(root):
        dn[:] = [d for d in dn if d not in SKIP_DIRS and not d.startswith(".")]
        for f in fn:
            if f.endswith(".html"):
                rel = os.path.relpath(os.path.join(dp, f), root).replace(os.sep, "/")
                out.append(rel)
    return sorted(out)


def url_path(rel):
    if rel == "index.html":
        return "/"
    if rel.endswith("/index.html"):
        return "/" + rel[: -len("index.html")]
    return "/" + rel


def h1_text(content):
    m = re.search(r"<h1[^>]*>(.*?)</h1>", content, re.S | re.I)
    return squash(m.group(1)) if m else ""


def section_for(cfg, rel):
    best = None
    for prefix, data in cfg["sections"].items():
        if rel.startswith(prefix + "/") and (best is None or len(prefix) > len(best[0])):
            best = (prefix, data)
    return best[1] if best else {"label": "teaching", "level": ""}


def classify(cfg, root, rel):
    base = os.path.basename(rel)
    if rel == "404.html":
        return "notfound"
    if rel.startswith("dashboard/"):
        return "private"
    if base == "quiz.html":
        return "quiz"
    if base == "assignment.html":
        return "assignment"
    if base == "index.html":
        if rel == "index.html":
            return "home"
        if url_path(rel) in cfg["pages"]:
            return "page"
        if os.path.exists(os.path.join(root, os.path.dirname(rel), "quiz.html")):
            return "lesson"
        return "page"
    return "other"


def lesson_name(cfg, root, rel):
    """Lesson display name = h1 of the lesson's own index.html."""
    idx = os.path.join(root, os.path.dirname(rel), "index.html")
    name = ""
    if os.path.exists(idx):
        name = h1_text(read(idx))
    if not name:
        name = os.path.basename(os.path.dirname(rel)).replace("-", " ").title()
    return fix_text(cfg, name)


def find_git_root(start):
    cur = start
    while True:
        if os.path.isdir(os.path.join(cur, ".git")):
            return cur
        parent = os.path.dirname(cur)
        if parent == cur:
            return None
        cur = parent


def git_lastmod(root, rel):
    try:
        gr = find_git_root(root)
        if not gr:
            return None
        r = subprocess.run(["git", "log", "-1", "--format=%cs", "--", os.path.join(root, rel)],
                           cwd=gr, capture_output=True, text=True, timeout=15)
        d = r.stdout.strip()
        return d if re.match(r"^\d{4}-\d{2}-\d{2}$", d) else None
    except Exception:
        return None


# --------------------------------------------------------------------------- per-page metadata
def make_title(cfg, name):
    sep, site = cfg["title_separator"], cfg["site_name"]
    full = name + sep + site
    return full if len(full) <= cfg["title_target_max"] else name


def lesson_question_count(root, rel):
    idx = os.path.join(root, os.path.dirname(rel), "index.html")
    if os.path.exists(idx):
        m = re.search(r"(\d+)\s+questions?", read(idx))
        if m:
            return int(m.group(1))
    return None


def lesson_lede(root, rel):
    """The visible <p class="lede"> under the h1 - the field the Quiz Maker calls 'description'."""
    idx = os.path.join(root, os.path.dirname(rel), "index.html")
    if not os.path.exists(idx):
        return ""
    m = re.search(r"<h1[^>]*>.*?</h1>\s*<p class=\"lede\">(.*?)</p>", read(idx), re.S)
    return squash(m.group(1)) if m else ""


def lesson_description(cfg, root, rel, existing_meta=""):
    """Prefer what the teacher typed; top up short ones; generate when empty."""
    section = section_for(cfg, rel)
    own = lesson_lede(root, rel)
    if not own:
        own = existing_meta
    if own and len(own) >= 90:
        return trim(own, cfg["description_max"])

    n = lesson_question_count(root, rel)
    phrase = section.get("phrase", "Lesson")
    label_ar = section.get("label_ar", phrase)
    if own and ARABIC_RE.search(own):
        tail = fmt(cfg, cfg["lesson_description_tail_ar"], label_ar=label_ar)
    elif n:
        tail = fmt(cfg, cfg["lesson_description_tail"], phrase=phrase, questions=n)
    else:
        tail = fmt(cfg, cfg["lesson_description_tail_noquiz"], phrase=phrase)
    limit = cfg["description_max"]
    if own:
        joined = own.rstrip(" .") + ". " + tail
        return joined if len(joined) <= limit else trim(own, limit)
    name = lesson_name(cfg, root, rel)
    with_name = name + ". " + tail
    if len(name) <= cfg.get("lesson_name_in_generated_description_max", 45) and len(with_name) <= limit:
        return with_name
    return trim(tail, limit)


def page_meta(cfg, root, rel, kind, content, prev_src=""):
    """Return dict(title, description, robots, schema_kind) for a page."""
    path = url_path(rel)
    ov = cfg.get("overrides", {}).get(path, {})
    meta = {"robots": None, "schema": None}

    if kind in ("private", "notfound"):
        meta["robots"] = "noindex, nofollow"
        return meta

    existing_meta = prev_src
    m = re.search(r'<meta\s+name="description"\s+content="([^"]*)"', content, re.I | re.S)
    if m and squash(m.group(1)):
        existing_meta = squash(m.group(1))
    meta["src_desc"] = existing_meta if kind == "lesson" else ""

    if kind in ("home", "page") and path in cfg["pages"]:
        p = cfg["pages"][path]
        meta["title"] = fmt(cfg, p["title"])
        meta["description"] = trim(fmt(cfg, p["description"]), cfg["description_max"])
        meta["schema"] = "home" if kind == "home" else "collection"
    elif kind == "page":
        name = fix_text(cfg, h1_text(content) or "Lessons")
        meta["title"] = make_title(cfg, name)
        meta["description"] = trim("{} \u2014 lessons, quizzes and assignments. {}".format(name, cfg["site_name"]),
                                   cfg["description_max"])
        meta["schema"] = "collection"
    elif kind == "lesson":
        name = lesson_name(cfg, root, rel)
        meta["title"] = make_title(cfg, name)
        meta["description"] = lesson_description(cfg, root, rel, existing_meta)
        meta["schema"] = "lesson"
    elif kind in ("quiz", "assignment"):
        name = lesson_name(cfg, root, rel)
        word = "Quiz" if kind == "quiz" else "Assignment"
        meta["title"] = make_title(cfg, name + " " + word)
        if kind == "quiz":
            meta["description"] = trim("Test yourself on {}: interactive quiz with instant feedback.".format(name),
                                       cfg["description_max"])
        else:
            meta["description"] = trim("Submit your {} assignment.".format(name), cfg["description_max"])
        allow = cfg.get("index_quiz_pages" if kind == "quiz" else "index_assignment_pages", False)
        if not allow:
            meta["robots"] = "noindex, follow"
    else:
        return {"robots": None, "schema": None, "skip": True}

    if ov.get("title"):
        meta["title"] = fmt(cfg, ov["title"])
    if ov.get("description"):
        meta["description"] = trim(fmt(cfg, ov["description"]), cfg["description_max"])
    if meta["robots"] is None:
        meta["robots"] = "index, follow, max-image-preview:large, max-snippet:-1"
    return meta


# --------------------------------------------------------------------------- structured data
def breadcrumb(cfg, root, rel, kind):
    site = cfg["site_url"]
    items = [("Home", site + "/")]
    parts = os.path.dirname(rel).split("/") if os.path.dirname(rel) else []
    cur = ""
    for i, part in enumerate(parts):
        cur = cur + part + "/"
        if not os.path.exists(os.path.join(root, cur, "index.html")):
            continue  # folder without a page of its own (e.g. /programming/baccalaureate/)
        if kind in ("lesson",) and i == len(parts) - 1:
            items.append((lesson_name(cfg, root, rel), site + "/" + cur))
        else:
            label = cfg["pages"].get("/" + cur, {}).get("crumb") or fix_text(cfg, part.replace("-", " ").title())
            items.append((label, site + "/" + cur))
    if len(items) < 2:
        return None
    return {
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": u} for i, (n, u) in enumerate(items)
        ],
    }


def json_ld(cfg, root, rel, kind, meta, canonical, lang):
    site = cfg["site_url"]
    person = {"@type": "Person", "name": cfg["author_name"], "url": cfg["author_url"]}
    schema = meta.get("schema")
    graph = []
    if schema == "home":
        site_node = {
            "@type": "WebSite", "@id": site + "/#website", "url": site + "/",
            "name": cfg["site_name"], "inLanguage": ["en", "ar"],
            "publisher": {"@id": site + "/#person"},
        }
        if cfg.get("site_alt_names"):
            site_node["alternateName"] = cfg["site_alt_names"]
        graph.append(site_node)
        graph.append(dict(person, **{"@id": site + "/#person", "sameAs": cfg.get("same_as", [])}))
    elif schema == "collection":
        graph.append({"@type": "CollectionPage", "name": meta["title"], "url": canonical,
                      "description": meta["description"], "inLanguage": lang,
                      "isPartOf": {"@type": "WebSite", "name": cfg["site_name"], "url": site + "/"}})
    elif schema == "lesson":
        section = section_for(cfg, rel)
        node = {"@type": "LearningResource", "name": lesson_name(cfg, root, rel), "url": canonical,
                "description": meta["description"], "inLanguage": lang,
                "learningResourceType": "Lesson", "author": person,
                "isPartOf": {"@type": "WebSite", "name": cfg["site_name"], "url": site + "/"}}
        if section.get("level"):
            node["educationalLevel"] = section["level"]
        graph.append(node)
    if schema in ("collection", "lesson"):
        bc = breadcrumb(cfg, root, rel, kind)
        if bc:
            graph.append(bc)
    if not graph:
        return ""
    doc = {"@context": "https://schema.org", "@graph": graph}
    body = json.dumps(doc, ensure_ascii=False, indent=2).replace("</", "<\\/")
    return '<script type="application/ld+json">\n' + body + "\n</script>"


# --------------------------------------------------------------------------- the block
def build_block(cfg, root, rel, kind, meta, lang):
    site = cfg["site_url"]
    canonical = site + url_path(rel)
    lines = []
    if meta.get("title"):
        img = site + cfg["og_image"] if cfg["og_image"].startswith("/") else cfg["og_image"]
        loc = "ar_EG" if lang == "ar" else "en_US"
        alt = "en_US" if lang == "ar" else "ar_EG"
        title, desc = esc(meta["title"]), esc(meta["description"])
        lines += [
            "<title>{}</title>".format(title),
            '<meta name="description" content="{}">'.format(desc),
            '<link rel="canonical" href="{}">'.format(esc(canonical)),
            '<meta name="robots" content="{}">'.format(meta["robots"]),
            '<meta name="author" content="{}">'.format(esc(cfg["author_name"])),
            '<meta property="og:site_name" content="{}">'.format(esc(cfg["site_name"])),
            '<meta property="og:type" content="website">',
            '<meta property="og:title" content="{}">'.format(title),
            '<meta property="og:description" content="{}">'.format(desc),
            '<meta property="og:url" content="{}">'.format(esc(canonical)),
            '<meta property="og:image" content="{}">'.format(esc(img)),
            '<meta property="og:image:width" content="1200">',
            '<meta property="og:image:height" content="630">',
            '<meta property="og:image:alt" content="{}">'.format(esc(fmt(cfg, cfg["og_image_alt"]))),
            '<meta property="og:locale" content="{}">'.format(loc),
            '<meta property="og:locale:alternate" content="{}">'.format(alt),
            '<meta name="twitter:card" content="summary_large_image">',
            '<meta name="twitter:title" content="{}">'.format(title),
            '<meta name="twitter:description" content="{}">'.format(desc),
            '<meta name="twitter:image" content="{}">'.format(esc(img)),
        ]
        ld = json_ld(cfg, root, rel, kind, meta, canonical, lang)
        if ld:
            lines.append(ld)
        if meta.get("src_desc"):
            lines.append("<!-- seo-src: {} -->".format(meta["src_desc"].replace("--", "\u2014")))
    else:
        lines.append('<meta name="robots" content="{}">'.format(meta["robots"]))
    return lines


STRIP_ALL = [
    r"<title>.*?</title>",
    r'<meta\s+name="description"\s+content="[^"]*"\s*/?>',
    r'<link\s+rel="canonical"[^>]*>',
    r'<meta\s+property="og:[^"]*"\s+content="[^"]*"\s*/?>',
    r'<meta\s+name="twitter:[^"]*"\s+content="[^"]*"\s*/?>',
    r'<meta\s+name="robots"\s+content="[^"]*"\s*/?>',
    r'<meta\s+name="author"\s+content="[^"]*"\s*/?>',
    r'<script type="application/ld\+json">.*?</script>',
]
STRIP_ROBOTS_ONLY = [r'<meta\s+name="robots"\s+content="[^"]*"\s*/?>']


def strip_loose(head, patterns):
    for pat in patterns:
        head = re.sub(r"[ \t]*" + pat + r"[ \t]*\r?\n?", "", head, flags=re.S | re.I)
    return head


def stamp(cfg, root, rel, apply_changes, stats):
    path = os.path.join(root, rel)
    content = read(path)
    original = content
    nl = "\r\n" if "\r\n" in content else "\n"
    kind = classify(cfg, root, rel)
    if kind == "other":
        return None

    # is this a page that already carries a block? -> meta from the ORIGINAL (block-free) copy
    prev = re.search(r"<!-- seo-src: (.*?) -->", content, re.S)
    prev_src = squash(prev.group(1)) if prev else ""
    stripped = BLOCK_RE.sub("", content)
    lang_m = re.search(r"<html[^>]*\blang=\"([a-zA-Z-]+)\"", stripped)
    lang = (lang_m.group(1).split("-")[0].lower() if lang_m else "en")
    meta = page_meta(cfg, root, rel, kind, stripped, prev_src)
    if meta.get("skip"):
        return None

    head_m = re.search(r"<head[^>]*>(.*?)</head>", stripped, re.S | re.I)
    if not head_m:
        return None
    head_old = head_m.group(0)
    head_new = strip_loose(head_old, STRIP_ROBOTS_ONLY if kind in ("private", "notfound") else STRIP_ALL)

    block_lines = build_block(cfg, root, rel, kind, meta, lang)
    block = START + "\n" + "\n".join(block_lines) + "\n" + END
    block = block.replace("\r\n", "\n").replace("\n", nl)   # keep the file's own line endings

    # insert after the viewport meta (or charset, or <head>)
    ins = None
    for pat in (r'<meta\s+name="viewport"[^>]*>', r'<meta\s+charset="[^"]*"\s*/?>', r"<head[^>]*>"):
        mm = re.search(pat, head_new, re.I)
        if mm:
            ins = mm.end()
            break
    head_final = head_new[:ins] + nl + block + head_new[ins:]
    new_content = stripped.replace(head_old, head_final, 1)

    # one URL per page: .../index.html -> .../  (internal links only)
    def _fix_link(m):
        stats["links"] += 1
        return m.group(1) + m.group(3)
    new_content = re.sub(r'(href="(?!https?:|//|mailto:|tel:)[^"#?]*?/)(index\.html)(["#?])', _fix_link, new_content)

    changed = new_content != original
    if changed and apply_changes:
        write(path, new_content)
    stats["changed" if changed else "same"] += 1
    return {"rel": rel, "kind": kind, "meta": meta, "changed": changed}


# --------------------------------------------------------------------------- sitemap / robots / manifest
def write_sitemap(cfg, root, results, apply_changes):
    site = cfg["site_url"]
    rows = []
    for r in results:
        if r["kind"] in ("home", "page", "lesson") and r["meta"].get("robots", "").startswith("index"):
            rows.append((url_path(r["rel"]), git_lastmod(root, r["rel"])))
    rows.sort(key=lambda t: (t[0] != "/", t[0]))
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for loc, lm in rows:
        out.append("  <url>")
        out.append("    <loc>{}</loc>".format(esc(site + loc)))
        if lm:
            out.append("    <lastmod>{}</lastmod>".format(lm))
        out.append("  </url>")
    out.append("</urlset>")
    text = "\n".join(out) + "\n"
    if apply_changes:
        write(os.path.join(root, "sitemap.xml"), text)
    return len(rows)


def write_robots(cfg, root, apply_changes):
    text = (
        "# Generated by tools/seo/seo_build.py\n"
        "User-agent: *\n"
        "Allow: /\n"
        "Disallow: /dashboard/\n"
        "\n"
        "Sitemap: {}/sitemap.xml\n".format(cfg["site_url"])
    )
    if apply_changes:
        write(os.path.join(root, "robots.txt"), text)


def write_manifest(cfg, root, apply_changes):
    p = os.path.join(root, "icons", "site.webmanifest")
    if not os.path.exists(p):
        return
    data = json.loads(read(p))
    data["name"] = cfg["site_name"]
    data["short_name"] = cfg["site_name"] if len(cfg["site_name"]) <= 14 else cfg["author_name"]
    data.setdefault("start_url", "/")
    data.setdefault("lang", "en")
    if apply_changes:
        write(p, json.dumps(data, indent=2, ensure_ascii=False) + "\n")


def make_og_image(cfg, root):
    try:
        from PIL import Image, ImageDraw, ImageFont
    except ImportError:
        print("  (Pillow not installed - skipped share image; `pip install pillow` then run with --og)")
        return False
    W, H = 1200, 630
    img = Image.new("RGB", (W, H), "#10233f")
    px = img.load()
    top, bot = (16, 35, 63), (47, 111, 237)
    for y in range(H):
        for x in range(W):
            t = min(1.0, max(0.0, (x / W) * 0.55 + (y / H) * 0.45))
            px[x, y] = tuple(int(top[i] + (bot[i] - top[i]) * t) for i in range(3))
    d = ImageDraw.Draw(img)

    def font(size, bold=True):
        cands = [
            r"C:\Windows\Fonts\segoeuib.ttf" if bold else r"C:\Windows\Fonts\segoeui.ttf",
            "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
            "/System/Library/Fonts/Supplemental/Arial Bold.ttf" if bold else "/System/Library/Fonts/Supplemental/Arial.ttf",
        ]
        for c in cands:
            if os.path.exists(c):
                return ImageFont.truetype(c, size)
        return ImageFont.load_default()

    d.ellipse((70, 88, 106, 124), fill="#ffffff")
    d.text((70, 250), cfg["site_name"], font=font(84), fill="#ffffff")
    d.text((70, 362), cfg.get("og_tagline", ""), font=font(38, False), fill="#dbe7ff")
    d.text((70, 520), cfg["site_url"].replace("https://", ""), font=font(30, False), fill="#bcd0f5")
    out = os.path.join(root, cfg["og_image"].lstrip("/"))
    os.makedirs(os.path.dirname(out), exist_ok=True)
    img.save(out, optimize=True)
    return True


# --------------------------------------------------------------------------- main
def run(root=None, check=False, og=False, quiet=False):
    root = os.path.abspath(root or DEFAULT_ROOT)
    cfg = load_config()
    apply_changes = not check
    stats = {"changed": 0, "same": 0, "links": 0}
    results = []
    for rel in walk_pages(root):
        r = stamp(cfg, root, rel, apply_changes, stats)
        if r:
            results.append(r)
    n_urls = write_sitemap(cfg, root, results, apply_changes)
    if apply_changes:
        write_robots(cfg, root, True)
        write_manifest(cfg, root, True)
        og_path = os.path.join(root, cfg["og_image"].lstrip("/"))
        if og or not os.path.exists(og_path):
            make_og_image(cfg, root)
    if not quiet:
        print("SEO build for {}  (site name: {!r})".format(root, cfg["site_name"]))
        print("  pages stamped: {}   unchanged: {}   internal links tidied: {}".format(
            stats["changed"], stats["same"], stats["links"]))
        print("  sitemap.xml: {} indexable URLs".format(n_urls))
        if check:
            print("  (--check: nothing was written)")
    return stats


if __name__ == "__main__":
    args = sys.argv[1:]
    root_arg = next((a for a in args if not a.startswith("--")), None)
    run(root_arg, check="--check" in args, og="--og" in args)
